<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Sachin\Session9Assignment\Block\DisplayBlock $block */
$entity = $block->getEntity();
?>
<h2>Entity Form</h2>
<form action="<?= $block->getActionUrl() ?>" method="post">
    <label for="name">Entity Name:</label><br>
    <input type="text" id="name" name="name" value="<?= !empty($entity) ? $entity->getName() : ''?>"><br>

    <label for="age">Entity Age:</label><br>
    <input type="text" id="age" name="age" value="<?= !empty($entity) ? $entity->getAge() : ''?>"><br>

    <label for="height">Entity Height:</label><br>
    <input type="text" id="height" name="height" value="<?= !empty($entity) ? $entity->getHeight() : ''?>"><br>

    <label for="is_employee">Is Employee:</label><br>
    <label for="is_employee">Employee</label>
    <input type="radio" id="is_employee" name="is_employee" value="employee" <?php echo (!empty($entity) && $entity->getIsEmployee()) ? "checked" : ''  ?> ><br><br>
    <label for="is_employee">Not Employee:</label>
    <input type="radio" id="is_employee" name="is_employee" value="not employee" <?php echo ( !empty($entity) && !$entity->getIsEmployee()) ? "checked" : ''  ?> ><br>

    <label for="short_description"> Entity Short Description:</label><br>
    <input type="text" id="short_description" name="short_description" value="<?= !empty($entity) ?
        $entity->getShortDesciption() : ''?>"><br>

    <label for="long_description">Entity Long Description:</label><br>
    <input type="text" id="long_description" name="long_description" value="<?= !empty($entity) ?
        $entity->getLongDescription() : ''?>"><br><br>
    <input type="hidden" name ="id" value="<?= $block->getRequest()->getParam('id') ?>">
    <input type="submit" value="Submit">
</form>

