<label for="first">First Number:</label>
<input type="text" id="first" name="first"><br><br>
<label for="second">Second Number:</label>
<input type="text" id="second" name="second"><br><br>
<input type="submit" value="Sum" id="submit"><br><br>

<label for="result">Result</label><br>
<input type="text" id="result" name="result">

<script type="text/javascript">
    requirejs(['Sachin_AssignmentSum/js/sum'], function(){
    });
</script>
